### ISSUE TITLE
Will this project get an update?

### ISSUE THREAD

**Issue by markjfisher** [nerd/discord.kt#1]
Hi, I wanted to use a discord bot for kotlin, and found this repo.

At the moment there's a couple of issues I found using it:

1. It hasn't been update for some of the new data that's sent back from server (which causes Jackson errors)
2. It hasn't  been pushed to maven as an artifact.

For my own application I've currently embed this project as a sub-module in my own project with a few `@JsonIgnoreProperties(ignoreUnknown = true)` annotations around types that haven't got the new fields.

I first wanted to check that you're ok with this, as it's your code, I'm not sure if the MIT license covers my usage, and if not, I'll find an alternative solution (it was fun understanding your code though).

Secondly, I was wondering if you're interested in bringing this up to date and deploying it so it can be pulled as a dependency rather than embed.

Cheers!

**Comment by nerd** [comment]
hi! 

thanks for checking out my project. the MIT license should cover anything, including your usage. I *can* attempt to update this project but if I'm being honest, I don't know if I can understand this code myself anymore :)

**Comment by markjfisher** [comment]
Well, if you don't mind pull requests, i can update it if I have time (I updated the dependencies too while I was at it locally).

Ultimately though, It'd be more useful as a maven artifact so it can be just include as a dependency, which involves registering with them and some other faff - I did it for my own domain recently, it wasn't too bad, and github users have an automatic artifact you can use without having to prove domain ownership.

**Comment by markjfisher** [comment]
ok, i'm closing this. no offence but i moved to a different api as i was chasing a long list of jackson exceptions here. this was a great start for me though, so thanks for providing the library.
